# Generated by Django 5.0 on 2023-12-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User name')),
                ('email', models.EmailField(max_length=254, verbose_name='User email')),
                ('message', models.TextField(verbose_name='User Message')),
            ],
        ),
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Forum name')),
                ('text', models.TextField(verbose_name='Forum text')),
            ],
        ),
    ]
